config/routes.rb
Rails.application.routes.draw do

  get "/statics/about" => "statics#about"
  get "/statics/contact" => "statics#contact"
  resources :restaurants
  resources :statics

  namespace :api do
    resources :beers, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :beerrestaurants, only: [:index]
  end

  get "/search" => "statics#search"

  resources :beers

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root 'statics#index' 

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

	def index
		@news_feed = Beerrestaurant.last(6).reverse
		@beer = Beer.all
		@restaurant = Restaurant.all
	end

	def search
		@restaurants = []
		@search_term = params[:search_term]
		@location = params[:location]

		if params[:range].present?
			@range = params[:range]
		else
			@range = "5"
		end

		@beer = Beer.beer_search(params[:search_term])

		@beer.each do |b|
			b.restaurants.near(@location, @range).each do |r|
				@restaurants << r
			end
		end

		if @search_term.empty?
			flash[:notice] = "You can't search without a search term; please enter a beer and retry!"
			redirect_to "/"
		elsif @location.empty?
			flash[:notice] = "You can't search without a location; please enter a location and retry!"
			redirect_to "/"
		else
			if @restaurants.length < 1
				flash[:notice] = "Sorry! We couldn't find any beer named '#{@search_term}' within #{@range} miles of #{@location}."
				redirect_to "/"
			else
				search_map(@restaurants)
			end
		end

	end

	def about
	end
	


	private

	# sets up the map hash for gmaps4rails
	def search_map(restaurants)
		@restaurants = restaurants
		@hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
			  marker.lat restaurant.lat
			  marker.lng restaurant.long
			  marker.infowindow "<a href='/restaurants/"+"#{restaurant.id}"+"'>#{restaurant.name}</a>"
		end
	end

end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_search_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { }, 
	internal: {id: 'search_map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/statics/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
</body>
</html>

app/views/statics/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>About Us</title>
  </head>
  <body>
    <div class="container marketing">
    <div class="row">
      <div class="featurette">
        <img class="featurette-image img-circle pull-right" src="http://icons.iconarchive.com/icons/flat-icons.com/flat/512/Beer-icon.png">
        <h2 class="featurette-heading">CrowdTap <br><span class="text-muted">Find your beer</span></h2>
          <p class="lead">CrowdTap is an American multinational corporation headquartered in Santa Monica, California. It develops web and mobile based app which publish crowd-sourced beer availability at their local bars, restaurant, and eateries.</p>
      </div>
      <hr class="featurette-divider">
      <div class="col-md-4 text-center">
        <%=image_tag("john.png", class: "img-circle-icon")%>
        <h3>John Ward</h3>
        <p><b>Biggest date fear:</b> Having stomach issues and clogging up a toilet, a la Dumb and Dumber
            If I never had to go back to school, I would be very happy.
            If I never got to see my family, I would be very sad.<br>
            <b>If you could be any animal, what would you be?</b>
            A dolphin. They're beautiful and supposedly use 20% of their brains -- brilliant!<br>
            <b>If you won the lottery, what would you do with your winnings?</b>
            I would give a large portion to my family, and then travel!<br>
            <b>What's your most embarrassing moment?</b>
            I have several -- once I was getting gas and the guy asked, "What kind of gas do you like?" and I thought he asked "What kind of guys do you like?" I responded, "Tall, dark, and handsome." He just stared at me and repeated the question.<br>
            <b>What is your greatest achievement to date?</b>
            Staying and living alone in California when my sister and brother-in-law went back home to Louisiana.</p>
        <p><a class="btn btn-default" href="https://github.com/jmward09">GITHUB</a></p>
      </div>
      <div class="col-md-4 text-center">
        <%=image_tag("bush.png", class: "img-circle-icon")%>
        <h3>Bush Anwar</h3>
        <p><b>Biggest date fear:</b> Guys who name drop and lie to impress
            I love it when my date opens the car door and tells you that you look nice -- right away.
            I hate it when my date gets too touchy-feely too soon.<br>
            <b>If you could be any animal, what would you be?</b>
            An eagle -- they mate for life, they fly and see the world above, they are strong and beautiful and represent the greatest country.<br>
            <b>If you won the lottery, what would you do with your winnings?</b>
            I would take my closest friends on a big multi-country vacation. Save half and donate the other half to schools for kids with learning disabilities like dyslexia.<br>
            <b>Do you prefer a man who wants to be pursued or a man who pursues you?</b>
            I'm a little old fashioned...I know times are changing but I still believe pursuing is part of being a man. Manly men approach women -- it shows confidence.<br>
            <b>If you really wanted to impress a man, what would you do?</b>
            I'd keep my mouth shut. :) Seriously, I think just being supportive and listening to what they have to say works best.</p>
        <p><a class="btn btn-default" href="https://github.com/busyra">GITHUB</a></p>
      </div>
      <div class="col-md-4 text-center">
        <%=image_tag("sam.png", class: "img-circle-icon")%>
        <h3>Sammy Amiri</h3>
        <p><b>Biggest date fear:</b> Running into recent exes
            If I never had to upset others, I would be very happy.
            If I never got to play with puppies, I would be very sad.<br>
            <b>If you could be any animal, what would you be?</b>
            A wild mustang. Free to run and explore, they're unpredictable and beautiful, and are loyal to their herd.<br>
            <b>If you won the lottery, what would you do with your winnings?</b>
            Adopt dogs and charter a jet for my friends and family to fly around Europe, with unlimited champagne and a hot air balloon ride over Greece.<br>
            <b>What's your most embarrassing moment?</b>
            I was in-depth stalking a guy's Facebook page and sent my friend a long, detailed text about my findings...except I sent it to him. Oops.<br>
            <b>What is your greatest achievement to date?</b>
            Getting my yoga certification because I've been able to inspire others to do yoga and become instructors!</p>
        <p><a class="btn btn-default" href="https://github.com/SamuelAmiri">GITHUB</a></p>
      </div>

      </div>
      <hr class="featurette-divider">
      <div class="featurette">
        <img class="featurette-image img-circle pull-left" src="http://ridgwood.questtech.netdna-cdn.com/wp-content/uploads/2013/04/obama-drinking-beer.jpg">
        <h2 class="featurette-heading">Drink <span class="text-muted">Up</span></h2>
        <p class="lead">“I drink to make other people more interesting.”  - Earnest Hemmingway
        </p>
      </div>
      <hr class="featurette-divider">

      
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <center><a href="http://crowdtap.herokuapp.com">·CrowdTap·</a></center>
      </footer>

    </div>
  </body>
</html>

app/views/statics/index.html.erb
<div style='width: 100%;'>
  <div id="mapwrapper"><div id="geolocation" style="width: 100%; height: 500px;"></div>
  <%= render "/layouts/home_map"  %></div>
</div>

<center><h3>--Recently Added Beers--</h3></center>
<% @news_feed.each do |f| %>
    <div class="col-md-4 col-sm-6">
      <div class="news_box">
        <div class="button_div first_button">
          <h4>
            <center> <a href="/beers/<%= f.beer_id%>"><%=@beer.find(f.beer_id).name%></a> <br><br>has been added to <br><br><a href="/restaurants/<%= f.restaurant_id%>"><%=@restaurant.find(f.restaurant_id).name%></a><br><br><%= @restaurant.find(f.restaurant_id).address%>
            </center>
          </h4>
              
        </div>
      </div>
    </div>
  <% end %>

app/views/statics/search.html.erb
<div style="width:100%;">
  <div id="search_map" style="width: 800%; height: 500px;">
    <%= render "search_map" %>
  </div>
</div>


<div class="col-md-16 col-md-offset-1">
  <h2>
    <%= "Restaurants Near: #{params[:location].titleize}" %>
  </h2>
  <table class="table table-striped table-hover">
    <thead>
      <th>Beer Name</th>
      <th>Restaurant</th>
      <th>Locations</th>
    </thead>
    <tbody>
      <% @beer.each do |b| %>
          <tr>
            <td>
            <%= link_to b.name, beer_path(b), method: "get" %>
            </td>   
              <td>
                <% b.restaurants.each do |r| %>
                  <%= link_to r.name, restaurant_path(r), method: "get" %>
              </td>
              <td>
                  
              </td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>