config/routes.rb
Rails.application.routes.draw do

  get "/statics/about" => "statics#about"
  get "/statics/contact" => "statics#contact"
  resources :restaurants
  resources :statics

  namespace :api do
    resources :beers, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :beerrestaurants, only: [:index]
  end

  get "/search" => "statics#search"

  resources :beers

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root 'statics#index' 

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :beerrestaurants
	has_many :beers, through: :beerrestaurants 
	geocoded_by :address, :latitude => :lat, :longitude => :long
	after_validation :geocode
end

app/controllers/api/restaurants_controller.rb
module API
  class RestaurantsController < ApplicationController
  	def index
      render json: Restaurant.all
    end
    def show 
    	render json: Restaurant.find(params[:id]).beers
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index

    if params[:search_term_bar].present?
      @client = GooglePlaces::Client.new(ENV["googleplaces_api_key"])
      searchTerm = params[:search_term_bar]
      
      if params[:location_bar].present?
        locationTerm = params[:location_bar]
      else 
        locationTerm = request.location.city
      end

      query =  searchTerm + " near #{locationTerm}"
      @place = @client.spots_by_query( query, :types => ['restaurant', 'bar'])
    end

    @restaurants = []

    if @place.present?
      @place.each do |p|
        @restaurants << p
      end
    end

    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.lat
      marker.lng restaurant.lng
      marker.infowindow restaurant.name
      marker.json({ title: restaurant.name })
    end

  end

  #GET "/restaurant/:id"
  def show
  	@restaurant = Restaurant.find(params[:id])
  	
    if params[:search_term].present?
			@beer = Beer.search(params[:search_term])
    end

    #sets up hash for map marker
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.lat
      marker.lng restaurant.long
      marker.infowindow "<a target='blank' href='https://www.google.com/maps/place/"+"#{restaurant.location}"+"'>Get Directions With Google Maps</a>"
      marker.json({ title: restaurant.name })
    end

	end


  def new
  	
  end

  def create
      @restaurant = Restaurant.find_or_create_by(restaurant_params)
          if @restaurant.save
              redirect_to restaurant_path(@restaurant)
          else
              render :index
          end
  end

  private
  	def restaurant_params
  		
  		params.require(:restaurant).permit(:name, :lat, :long, :place_id, :location, :rating, :price)

  	end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :beer_ids %><br>
    <%= f.text_field :beer_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { mapTypeId: google.maps.MapTypeId.ROADMAP, maxZoom: 25}, 
	internal: {id: 'restaurant_map'}}, function(){

  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  
  if(markers) {
    handler.bounds.extendWith(markers);
  	handler.fitMapToBounds();
  }
  else (navigator.geolocation)
          navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);
};
</script>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <div id="restaurant_map">
    <%= render "restaurant_map" %>
  </div>

  <!-- Search form for Restaurants/Bars -->
<div id="restaurant-index-body">

  <h2> Find and choose the Restaurant to add a Beer </h2>
    <form class="navbar-form navbar-center", role="search">
      <%= form_tag({:controller=>"restaurants", :action=>"index"}, method: :get) do %>
      <div class="form-group-lg">
              <%= text_field_tag :search_term_bar, '', :placeholder => "Restaurant/Bar", :class => "form-control" %>
              <%= text_field_tag :location_bar, '', :placeholder => "Location", :class => "form-control" %>
              <%= submit_tag 'Search', name: nil, :class => "btn btn-lg" %>
          <% end %>
      </div>
    </form>

  <!-- Display all results from search -->
  <% if @restaurants.present? %>
    <div class="row">
    <%# raise @restaurants.inspect %>
    <% @restaurants.each do |x| %>
      unless x.place_id 
      <div class="col-xs-6 col-md-3">
        <%= x.name %> <br/>
        <%= image_tag(x.icon) %> <br/>
        <%= x.formatted_address %> <br/>
        <%= x.rating %><br/>
        <%= x.price_level %><br/>
        <%= x.lng %>
        <%= x.lat %>


        <%= form_tag({:controller=>"restaurants", :action=>"create"}, method: :post) do %>
            <%= hidden_field_tag "restaurant[name]", x.name %>
            <%= hidden_field_tag "restaurant[lat]", x.lat %>
            <%= hidden_field_tag "restaurant[long]", x.lng %>
            <%= hidden_field_tag "restaurant[place_id]", x.place_id %>
            <%= hidden_field_tag "restaurant[location]", x.formatted_address %>
            <%= submit_tag 'Add some Beers', name: nil %>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant Page</title>
</head>
<body>

<div style="width:100%;">
  <div id="restaurant_map">
    <%= render "restaurant_map" %>
  </div>
</div>
	
<div id="contrainer">
	<h2> <%= @restaurant.name %></h2>
	<h3> <%= @restaurant.location %></h3>

	<%= form_tag({:controller=>"restaurants", :action=>"show"}, method: :get) do %>
		<%= text_field_tag :search_term %>
	    <%= submit_tag 'Search for a Beer', name: nil %>
	<% end %>

	<div class="col-md-6">
		<% if @beer.present?%>
			<% if @beer['data'].present? %>
			<div class="row">
				<% @beer['data'].each do |f|  %>
					<div class="col-xs-6 col-md-3">
					<%= image_tag((f['labels']['medium'] if f['labels'].present?), :class => "thumbnail") %>
					  <%= form_tag({:controller=>"beers", :action=>"create", :id => @restaurant.id}, method: :post) do %>
				          <%= hidden_field_tag "beer[name]", f['name'] %>
				          <%= hidden_field_tag "beer[brewery]", f['breweries'][0]["name"] %>
				          <% if f["style"].present? %>
				    	  <%= hidden_field_tag "beer[style]", f["style"]["shortName"] %>
				    	  <% end %>
				    	  <% if f["labels"].present? %>
				    	  <%= hidden_field_tag "beer[labels]", f["labels"]["medium"]  %>
				    	  <% end %>
				    	  <%= f["description"].present? %>
		  		    	  <% if f["description"].present? %>
				    	  <%= hidden_field_tag "beer[description]", f["description"] %>
				    	  <% end %>
				    	  <%= hidden_field_tag "beer[breweryDB_id]", f["id"] %>
				      	  <%= submit_tag 'Add Beer', name: nil, :class => "btn btn-default" %>
		      		  <% end %>
		  		  	</div>
				<% end %>
			<% end %>
			</div>
		<% end %>
		

		<h1>What's on Tap?</h1>
		<div class="row">
			<% @restaurant.beers.each do |f| %>
			<div class="container col-sm-4" >
				<div class="span3">
				  	<div class="thumbnail">
					<%= image_tag(f.labels) %><br />
					<div class="caption">
						<div class="row-fluid">
				            <div class="span6">
				            	<%= link_to "Check it out", beer_path(f.id), :class => "btn btn-block btn-info" %>
				        	</div>
			    		</div>
					</div>
				  	</div>
				</div>
		  	</div>
			<% end %>
		</div>
	</div>
</div>

</body>
</html>