config/routes.rb
Rails.application.routes.draw do

  get "/statics/about" => "statics#about"
  get "/statics/contact" => "statics#contact"
  resources :restaurants
  resources :statics

  namespace :api do
    resources :beers, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :beerrestaurants, only: [:index]
  end

  get "/search" => "statics#search"

  resources :beers

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root 'statics#index' 

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	has_many :beerrestaurants 
	has_many :restaurants, through: :beerrestaurants 

	# BreweryDB API search
	# @param term is a string (beer name)
	def self.search term
		# remove any spaces from search term and replace with _
		remspace = term.downcase.tr(" ", "_")
		# combine url with search term and API Key
		uri = "http://api.brewerydb.com/v2/search?q='#{remspace}'&type=beer&withBreweries=Y&key=#{ENV['brewerydb_api_key']}"

		HTTParty.get uri
	end

	def self.beer_search search
	    where('name ILIKE ?', "%#{search}%")
  	end

end

app/controllers/api/beers_controller.rb
module API
  class BeersController < ApplicationController
  	def index
      render json: Beer.all
    end
    def show 
    	render json: Beer.find(params[:id]).restaurants
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])
    
    @restaurants = []

    @beer.restaurants.each do |r|
      @restaurants << r
    end

    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.lat
      marker.lng restaurant.long
      marker.infowindow "<a href='/restaurants/"+"#{restaurant.id}"+"'>#{restaurant.name}</a>"
      marker.json({ title: restaurant.name })
    end
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @restaurant = Restaurant.find(params[:id])
    @beer = Beer.where(beer_params).first_or_create 
          if @beer.save
              begin
                @beer.restaurants << @restaurant
                redirect_to restaurant_path(@restaurant.id)
              rescue
                flash[:warning] = "The Beer already exists"
                redirect_to restaurant_path(@restaurant.id)
              end

          else
              render :show
          end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_beer
      @beer = Beer.find(params[:id])
    end

    def beer_params
      params.require(:beer).permit(:name, :brewery, :style, :breweryDB_id, :labels, :description, restaurant_ids:[])
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { }, 
	internal: {id: 'beer_map'}}, function(){
		if(navigator.geolocation)
        	navigator.geolocation.getCurrentPosition(displayOnMap);

  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  
  if(markers) {
	handler.bounds.extendWith(markers);
  	handler.fitMapToBounds();
  }
  else {
	handler.map.centerOn(marker);
  }
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });

};
</script>

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.text_field :brewery %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :restaurant_ids %><br>
    <%= f.text_field :restaurant_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brewery</th>
      <th>Style</th>
      <th>Restaurant ids</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.brewery %></td>
        <td><%= beer.style %></td>
        <td><%= beer.restaurant_ids %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid" id="main">
  <div class="row">
  	<div class="col-xs-8" id="left">

  	<%= @beer.inspect %>


  	<h2><%=@beer.name%></h2>
	
	<%= image_tag(@beer.labels)%>

	<p>
	  <strong>Brewery:</strong>
	  <%= @beer.brewery %>
	</p>

	<p>
	  <strong>Style:</strong>
	  <%= @beer.style %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @beer.description %>
	</p>

	<p>
	  <strong>You can find it at:</strong>
	  <% @restaurants.each do |r| %>
	  	<%= link_to r.name, restaurant_path(r), method: "get" %>
	  	<%= r.address %>
	  <% end %>
	</p>

	</div>
  </div>
</div>



<div id="beer_map">
	<%= render "beer_map" %>
</div>